### PR TITLE
Challenge

### PR DESCRIPTION
**Pull request by SMITHsharon**
assignment done / functionality tested / no styling

### CODE REVIEW

**Comment by rousell** [comment]
@SMITHsharon This looks great! Really well organized code :)

My only two small suggestions would be to (1) remove any unused, commented code out of your javascript, and (2) try to make the entire tree print out within the same console log statement! You should be able to use an escaped new line character to do this ("\n")

**Comment by SMITHsharon** [comment]
@rousell 
I've made the changes. 
Should I merge the prior first, then do a new pull request?
Or push up the corrections? 
#processQuestion

**Comment by rousell** [comment]
@SMITHsharon just push up the corrections! the pull request will update with your changes

**Comment by SMITHsharon** [comment]
@rousell 
done!

**Comment by rousell** [comment]
@SMITHsharon looks great! 👍

**Comment by SMITHsharon** [comment]
:)

**Pull request merged**
